name: builder
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
    - name: Clone image source scripts for testers
      run: git clone https://github.com/kartheek542/hostcode-testers.git

    - name: Clone image source scripts for hostcode-backend
      run: git clone https://github.com/kartheek542/hostcode-backend.git

    - name: Check docker version
      run: docker --version

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: kartheek542
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push hostcode-backend
      run: docker build -t kartheek542/hostcode:backend-1.0 . && docker push kartheek542/hostcode:backend-1.0
      working-directory: hostcode-backend/

    - name: Build and push jdk-17
      run: docker build -t kartheek542/hostcode:tester-1 . && docker push kartheek542/hostcode:tester-1
      working-directory: hostcode-testers/java/jdk17/

    - name: Build and push worker-pod
      run: docker build -t kartheek542/hostcode:job-worker . && docker push kartheek542/hostcode:job-worker
      working-directory: hostcode-testers/worker-pod/