name: start-app
on: workflow_dispatch
jobs:
  provision-infra:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.CLOUD_REGION }}
    runs-on: ubuntu-latest
    steps:
    - name: Clone terraform scripts
      run: echo "Cloning Terraform code"
    - name: Checking the cloud credentials
      run: echo "The values are $AWS_ACCESS_KEY_ID and $AWS_SECRET_ACCESS_KEY and $AWS_REGION"
    - name: Generate ssh keys
      run: ssh-keygen -t rsa -b 4096 -N "" -f "aws_terraform_key"
    - name: List the contents of the directory
      run: ls -la
    - name: Initialize Terraform
      run: echo "this is terraform init"
    - name: Validate Terraform
      run: echo "this is terraform validate"
    - name: Apply Terraform
      run: echo "this is terraform apply"
  ensure-config:
    needs: provision-infra
    runs-on: ubuntu-latest
    steps:
      - name: This is for ansible
        uses: actions/checkout@v4
