name: ui_test
on: workflow_dispatch
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Clone image source scripts for testers
      id: nodejs-ip-step
      run: echo "1.2.3.4" >> "$GITHUB_OUTPUT"
    outputs:
      nodejs_public_ip: ${{ steps.nodejs-ip-step.outputs.value }}

  build-ui-image:
    env:
      VITE_API_URL: "http://${{ needs.setup.outputs.nodejs_public_ip }}/api"
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: test environment
      run: env | grep "VITE"
