name: ui_test
on: workflow_dispatch
jobs:
  build-ui-image:
    runs-on: ubuntu-latest
    steps:
    - name: Clone image source scripts for testers
      run: git clone https://github.com/kartheek542/hostcode-ui.git
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.18.0'

    - name: Check node version
      run: node --version

    - name: Check docker version
      run: docker --version

    # - name: Login to DockerHub
    #   uses: docker/login-action@v3
    #   with:
    #     username: kartheek542
    #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # - name: Build source
    #   run: docker build -t kartheek542/hostcode:backend-1.0 . && docker push kartheek542/hostcode:backend-1.0
    #   working-directory: hostcode-ui/

    # - name: Build and push hostcode-backend
    #   run: docker build -t kartheek542/hostcode:backend-1.0 . && docker push kartheek542/hostcode:backend-1.0
    #   working-directory: hostcode-ui/