name: workflow-test
on: workflow_dispatch
jobs:
  provision-infra:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.CLOUD_REGION }}
    runs-on: ubuntu-latest
    steps:
    - name: Check python3 version
      run: python3 --version
    - name: Check python3 path
      run: which python3
